### ISSUE TITLE
Diplomacy alliance tab always "selected".

### ISSUE THREAD

**Issue by MaLiN2223** [swat-web/IkaEasy#26]
Bug reported by Nicolaescu Madalin in [http://ikariam-easy.com/update-2-0-1-bugs/#disqus_thread](http://ikariam-easy.com/update-2-0-1-bugs/#disqus_thread).

> In the diplomacy tab, no matter where you are, the alliance tab stay "marked"
> ![Image](https://cloud.githubusercontent.com/assets/7461791/19281265/bb6233b6-8fe9-11e6-8761-6efbf2a015f7.jpg)

**Comment by MaLiN2223** [comment]
Bug has been confirmed by me.

**Comment by swat-web** [comment]
Fixed in https://github.com/swat-web/IkaEasy/commit/d6e5c00001d2211795c4df4d1382903ae26fc8f2
