### ISSUE TITLE
Shipyard update problem 

### ISSUE THREAD

**Issue by MaLiN2223** [swat-web/IkaEasy#27]
Bug reported by Nicolaescu Madalin in [http://ikariam-easy.com/update-2-0-1-bugs/#disqus_thread](http://ikariam-easy.com/update-2-0-1-bugs/#disqus_thread)
Shipyard cannot be upgraded to level higher than 32 using script.
![Image](https://cloud.githubusercontent.com/assets/7461791/19281294/ee6f912c-8fe9-11e6-86a8-9199c124c82c.jpg)

**Comment by swat-web** [comment]
Bug is fixed #31 .
Thanks MaLiN2223.
