### ISSUE TITLE
Tooltip wrong values

### ISSUE THREAD

**Issue by MaLiN2223** [swat-web/IkaEasy#28]
The bug was posted by Gabriel Drugan in [http://ikariam-easy.com/update-2-0-1-bugs/#disqus_thread](http://ikariam-easy.com/update-2-0-1-bugs/#disqus_thread).

> Hi Vlad, good work, i have this bug where somehow on tooltip is the wrong values. I've tested on different Chrome User on the same PC, same version of Chrome and there is showing the correct amount. I've tried reinstall the plugin, delete cache/cookies from the beginning of time, i'm still having problems.
> ![Image](https://cloud.githubusercontent.com/assets/7461791/19281437/940e832c-8fea-11e6-8446-1282b622e080.jpg)

**Comment by swat-web** [comment]
User wrote in comments:

> Hi, there was a hidden popup in chrome to allow scripts from unsecured sites. After i've allowed that i didn't encountered any problem. Keep up the good job.

So I'm closing the issue.
