### ISSUE TITLE
Always selected "IkariamEasy" in options

### ISSUE THREAD

**Issue by MaLiN2223** [swat-web/IkaEasy#29]
IkariamEasy tab always looks like it is selected.
Possible connection to #26 .
Screen : 
![Image](https://cloud.githubusercontent.com/assets/7461791/19281573/21c9fd90-8feb-11e6-8b5f-98ff8349167b.PNG)

**Comment by swat-web** [comment]
https://github.com/swat-web/IkaEasy/commit/d6e5c00001d2211795c4df4d1382903ae26fc8f2
